### ISSUE TITLE
Fix the dark mode toggle and sidebar area

### ISSUE THREAD

**Issue by PushpenderSaini0** [acenturyandabit/fortknight#104]
As of now the sidebar takes over the dark mode toggle area leaving only a small space for it's activation.

![image](https://github.com/user-attachments/assets/6bdace1b-55f9-46c0-9003-2f1e50ddd481)

## Demo

https://github.com/user-attachments/assets/7ac68b7f-9061-4676-9fe6-8508c9dd1aca

**Comment by CommonHouseCat** [comment]
Hello @PushpenderSaini0, I would like to work on this. Can you assign this issue to me?
