### ISSUE TITLE
Bug: Is Square Safe? Function

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#13]
Make a function which, given a square index, checks whether or not the square is safe (if the knight will be taken on the next turn.)

**Comment by dannie-zhang** [comment]
Hello!

Victoria and I would like the reserve this issue as well!

Thanks, 
Dannie

**Comment by acenturyandabit** [comment]
Actually, one minor issue: pieces which are still growing show up as threatening even though they can't move.

**Comment by VelialCypher** [comment]
I fix it :)
