### ISSUE TITLE
Create the highscores page

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#2]
Create the highscores page using the fragments set out in the code.

**Comment by jSAMUELj** [comment]
Is this issue still available ?

**Comment by acenturyandabit** [comment]
Yeah, definitely, go for it. Right now, the highscore is just a single, global highscore displayed on the front tab. If you could make a separate tab with multiple highscores for the different gamemodes, that'd be a good achievement.

**Comment by acenturyandabit** [comment]
This was done by Roshak's PR.
