### ISSUE TITLE
Feature: Add pawns

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#20]
Pawns always start on the 2nd row and move and take like standard pawns. If they reach the top row, they get promoted to queens!

**Comment by dannie-zhang** [comment]
Hi!

We would like the reserve this issue as well! :)

Thanks,
Dannie

**Comment by acenturyandabit** [comment]
Hello, 
If you're reading this, I believe Dannie has finished her course and so this issue is back up for graps.

**Comment by cethemaco** [comment]
Hello, 
I would like to work on this!

**Comment by cethemaco** [comment]
Hello, 

I would like to reserve this issue and take care of adding pawns :)

**Comment by acenturyandabit** [comment]
Hi, great to hear! Hope you have fun :)

It would be pretty cool to have the pawn start from 'any' second row, with a little arrow to indicate its direction. 

Now that I think about it, maybe even have it start on either the first OR second row in any direction, for maximum chaos :D
