### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#23]
Allow the player to use the home keys to control the knight:

```
Q WE R
A SD F
```
QA move the knight two left and one up/down;
WE move the knight two up and one left/right;
SD move the knight two down and one left/right;
RF mofe the knight two right and one up/down.

**Comment by vicdjy** [comment]
Hi Steve,
We are thinking about taking this issue as well! I was wondering what do you mean by one up/down? For example, if QA is pressed, do we just randomly select up/down for the user? How to distinguish between up and down?

Thank you,
Jiayang Ding

**Comment by acenturyandabit** [comment]
Hi Jiaying,

The Q key is higher than the A key, so the Q is up and the A is down. Similarly the W is left and the E is right, and so on.

**Comment by acenturyandabit** [comment]
This issue is again up for grabs on account of vicdjy finishing her course.

**Comment by larue-jordan** [comment]
Hi Steve,
I would like to try and contribute towards this improvement.
-Jordan LaRue

**Comment by acenturyandabit** [comment]
Sweet, go for it!

**Comment by larue-jordan** [comment]
@acenturyandabit I have most of this implemented.  A thought I had is, should any one of the key combinations be able to be clicked at any time? For instance if the knight was on the left border and the user hits either q, a, w, or s should that flash the square indicated by that move red? or should we just ignore those keystrokes?  I know there is logic to handle invalid moves for clicking but I figured I would get clarification before continuing.
-Jordan

**Comment by acenturyandabit** [comment]
Hi Jordan,
Good to hear it's going well! Flashing invalid squares red is a great idea :) go for it

**Comment by acenturyandabit** [comment]
@larue-jordan im a little busy atm, will get to it in due time. thanks
