### ISSUE TITLE
Arcade mode balancing

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#30]
Arcade mode is fun, but it's way too easy right now! 
- Give pieces only 1 turn before spawning into a big piece
- Make a countdown timer visible on screen for the enemy moves

**Comment by PoisonedPoi** [comment]
Hello,
I am new to open source projects and I would like to try to implement this change to get some experience both in open source and using html/scripts.  I noticed on an earlier issue there was a pull request to re factor and cleanup the code and possibly split it into different files recently in this past week.  I was wondering If I should start making changes to the main index.html and get that working or wait/modify the new pull request as it seems like it changes a lot.

**Comment by acenturyandabit** [comment]
Hiya, thanks for checking in. Let me merge in that PR right now. I'll get back to you in an hour tops.

**Comment by acenturyandabit** [comment]
Right, you're good to go!

**Comment by PoisonedPoi** [comment]
Thanks for getting back to me so fast and doing the merge, ill keep you updated on my progress as I go.

**Comment by PoisonedPoi** [comment]
I addressed this in https://github.com/acenturyandabit/fortknight/pull/40.
