### ISSUE TITLE
Bug: Switching to dark mode hides text

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#55]
Steps to reproduce:
1. Switch to dark mode
2. Start a classic (or any) game.
3. Lose.
4. Go to the achievements screen - the text is hidden (black on black). Some text in the front is also hidden (black on black).

Fix by changing the CSS somehow.

**Comment by PushpenderSaini0** [comment]
Hi i have find the problem , the `renderHighscores` removes the styles on the text and this can be easily solved by calling the check mode function in the end of the `renderHighscores` function,
You can assign the issue to me i will soon submit a PR for it !
