### ISSUE TITLE
Create a License

### ISSUE THREAD

**Issue by HackerFrosch** [acenturyandabit/fortknight#73]
I would definitely add a license to communicate clearly to other people what they can and cant do with the sourcecode. I would prefer the GNU GLPv3 License
https://choosealicense.com/licenses/gpl-3.0/

or the MIT License if anyone should be allowed to distribute Closed-Source-Versions of it.
https://choosealicense.com/licenses/mit/

**Comment by acenturyandabit** [comment]
I back GPL3!

**Comment by HackerFrosch** [comment]
perfect then i'll create one
