### ISSUE TITLE
Project where the knight can move

### ISSUE THREAD

**Issue by Theo-Stefan** [acenturyandabit/fortknight#84]
Hey there, first of all I'd like to say im a big chess fan and this project is pretty cool!

i'd like to contribute to this project and add a little detail for the people that are not really familiar with the game.
My idea is to simply project where the knight is able to move on the board. For someone that can be an annoying thing so i will make it as nice as possible with of course the option to remove that visual.
Can I work on that please?
![image](https://user-images.githubusercontent.com/72577715/213862644-04b59233-3cf8-464e-aafd-8fb054a833c1.png)

**Comment by acenturyandabit** [comment]
Hey Theo! Sure, be my guest :D

**Comment by Theo-Stefan** [comment]
> Hey Theo! Sure, be my guest :D

thank you!

**Comment by Theo-Stefan** [comment]
> Hey Theo! Sure, be my guest :D

I have solved and completed this issue, already done a pull request and you may review it, thanks :)

**Comment by acenturyandabit** [comment]
Done by #85
