### ISSUE TITLE
Improved resize behavior

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#93]
Currently, when on a desktop, going from fullscreen to 50% of screen by width creates a huge chessboard which is difficult to click. Instead, there should be a smaller board with some padding to the edge of the screen.

**Comment by VelialCypher** [comment]
Maybe transfer the board to canvas?

For more flexible scaling, since now there are problems with both the scale and the location of points of movement, figures for any screen scaling.

**Comment by acenturyandabit** [comment]
Hmm, that's an interesting idea. I prefer using vector graphics over direct pixel draws; and not using canvas allows us to use CSS effects, which may be more friendly to developers. I'm sure there are canvas ways of creating the same effect, but would need proof that this would not come at a cost of additional complexity.

**Comment by acenturyandabit** [comment]
Also I suspect the resizing issue is a layout issue; even if we did use canvas, we would need to size the canvas appropriately alongside the instructions etc, which would be a css job.

**Comment by VelialCypher** [comment]
This is just a suggestion, I don't insist on it as it's a lot of work :)

I'm almost done with the zoom issue. But while solving this problem, I came up with some improvements in the display of pieces on the field and signs of growth and direction of pawns. It remains to fix the scale when the media query is triggered.

**Comment by VelialCypher** [comment]
These are my suggestions for displaying shapes.
![fig1](https://user-images.githubusercontent.com/65967939/222561547-5539d353-3dd7-4eaa-b243-eb978da6a405.png)
![fig2](https://user-images.githubusercontent.com/65967939/222561550-eb1f09c9-280e-4151-8b39-f7cc55bc2d36.png)
![fig3](https://user-images.githubusercontent.com/65967939/222561552-64ba1f8b-18cb-43b2-b473-e21ddbdfc2d8.png)

**Comment by VelialCypher** [comment]
I think it looks nice.
![image](https://user-images.githubusercontent.com/65967939/222567356-ca645988-d716-4c1a-91fd-9604dc001c93.png)

**Comment by VelialCypher** [comment]
I finished my work, this solution is not durable, since most likely the layout needs to be redone...

**Comment by VelialCypher** [comment]
I want to ask a question about the code.

Do you mind ES6 classes? In the code, I see only constructor functions, I wanted to ask: can I use sugar in the form of classes?

**Comment by acenturyandabit** [comment]
Yeah go for it! caniuse says they're pretty well supported :)

**Comment by acenturyandabit** [comment]
> I think it looks nice. ![image](https://user-images.githubusercontent.com/65967939/222567356-ca645988-d716-4c1a-91fd-9604dc001c93.png)

 I do like that the board is cleaner if the pieces fit the squares entirely; however, I have some counterpoints:
- The current system where the about-to-spawn pieces are smaller is a nice visual indicator that they're not a threat yet; and I like this compared to having them the same size with a number in the corner. 
- Filling up the square entirely with the piece may make it difficult to confirm whether a queen / bishop is on a white square or a black square.

So right now I would prefer to keep the current rendering. But as always, happy to be convinced otherwise with reasons :)

**Comment by VelialCypher** [comment]
1. It looks good when the figure has no background. Therefore, I can suggest changing the colors of the board - so that the figures do not merge with it and remove the background filling with white.
2. Solved by the first one :)

**Comment by VelialCypher** [comment]
![image](https://user-images.githubusercontent.com/65967939/222957146-3e9d98b5-f2cd-4abe-a1b4-e897e9811e0e.png)

**Comment by acenturyandabit** [comment]
Woa that looks sleek! I like it :D

I would still like the pieces to be slighty smaller when they are spawning though - any chance we could put that back in?
